<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
	  <LangVersion>preview</LangVersion>
	</PropertyGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Enums\**" />
	  <Compile Remove="Enums\**" />
	  <EmbeddedResource Remove="Enums\**" />
	  <None Remove="Enums\**" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Include=".gitignore" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Content\Textures\Extra\" />
	</ItemGroup>

	<!-- References -->

</Project>